before_commands:
    - "composer install --dev --prefer-source"

tools:
    php_code_coverage:
        enabled: true
        test_command: ./vendor/bin/phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
            exclude_paths: ["src/MCNElasticSearch/Listener/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build/*", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true
